Static Function cn_GetEnv()
	Local aParameters := {}
	veCC := GetEnv ("CC")
	veCDBG := GetEnv ("CDBG")
	veCFLAGS := GetEnv ("CFLAGS")
	veCHARSET := GetEnv ("CHARSET")
	veCLIP_CMDSTR := GetEnv ("CLIP_CMDSTR")
	veCLIPLIB := GetEnv ("CLIPLIB")
	veCLIPLIBS := GetEnv ("CLIPLIBS")
	veCLIP_LOCALE_ROOT := GetEnv ("CLIP_LOCALE_ROOT")
	veCLIP_MODULE := GetEnv ("CLIP_MODULE")
	veCLIP_NAMES := GetEnv ("CLIP_NAMES")
	veCLIPROOT := GetEnv ("CLIPROOT")
	veCLIPSLIB := GetEnv ("CLIPSLIB")
	veCOMPILE_FLAG := GetEnv ("COMPILE_FLAG")
	veCOPT := GetEnv ("COPT")
	veINCLUDE_FLAG := GetEnv ("INCLUDE_FLAG")
	veLC_ALL := GetEnv ("LC_NAME")
	veLIBSUF := GetEnv ("LIBSUF")
	veLANG := GetEnv ("LANG")
	veOBJSUF := GetEnv ("OBJSUF")
	veOUT_FLAG := GetEnv ("OUT_FLAG")
	veSFLAGS := GetEnv ("SFLAGS")
	veSLIBSUF := GetEnv ("SLIBSUF")
	veSOBJSUF := GetEnv ("SOBJSUF")
	veCLIP_LANG := GetEnv ("CLIP_LANG")
	veCLIP_HOSTCS := GetEnv ("CLIP_HOSTCS")
	veCLIP_CLIENTCS := GetEnv ("CLIP_CLIENTCS")
	veCLIP_LOCALE := GetEnv ("CLIP_LOCALE")
	veCLIP_LOGLEVEL := GetEnv ("CLIP_LOGLEVEL")
	veCLIP_SCANMODE := GetEnv ("CLIP_SCANMODE")
	veCLIP_SCANSTART := GetEnv ("CLIP_SCANSTART")
	veCLIP_SCANSTOP := GetEnv ("CLIP_SCANSTOP")
	veCLIP_KEYMAP := GetEnv ("CLIP_KEYMAP")
	veCLIP_LINECHARS := GetEnv ("CLIP_LINECHARS")
	veCLIP_DLINECHARS := GetEnv ("CLIP_DLINECHARS")
	veCLIP_COLORMAP := GetEnv ("CLIP_COLORMAP")

	Return aParameters

