#
# call from all configure files
#
#function CreateMakefile_01 ()
#	{
#		source ./configure.ini
		echo "##"  																						>Makefile.01
		echo "## automatically generated by configure"  									>>Makefile.01
		echo "## functions CreateMakefile_01"  												>>Makefile.01
		echo "##"  																						>>Makefile.01
		echo "##  $PWD/Makefile.01"  																>>Makefile.01
		echo "##"  																						>>Makefile.01
		echo "##  $ProgName"  																		>>Makefile.01
		echo "##  $PROG"  																			>>Makefile.01
		echo "##"  																						>>Makefile.01
		echo "## functions CreateMakefile_01"  												>>Makefile.ini
		echo "##"  																						>>Makefile.ini
		echo "##  $PWD/Makefile.ini"  															>>Makefile.ini
		echo "##"  																						>>Makefile.ini
		echo "##  $ProgName"  																		>>Makefile.ini
		echo "##"  																						>>Makefile.ini
		echo ""  																						>>Makefile.ini
		echo ""  																						>>Makefile.01
		echo ""  																						>>Makefile.01
		echo "export c_files=$c_files" 															>>Makefile.01
		echo "export ch_files=$ch_files" 														>>Makefile.01
		echo "export h_files=$h_files" 															>>Makefile.01
		echo "export prg_files=$prg_files" 														>>Makefile.01
		echo "export ADDOBJS=$ADDOBJS"	 														>>Makefile.01
		echo "export ADDLIBS=$ADDLIBS"	 														>>Makefile.ini
		echo "export C_FLAGS=$C_FLAGS" 																>>Makefile.ini
		echo "export CLIP_FLAGS=$CLIP_FLAGS" 													>>Makefile.ini
		echo "export PROG      		=   	$PROG"												>>Makefile.01
		echo "export Main_h        	= 		$Clip_I_Dir/*.h" 								>>Makefile.01
		echo "export Main_h        	+= 	$Clip_I_Dir/*.ch" 							>>Makefile.01
		echo ""  																						>>Makefile.01
		echo ""  																						>>Makefile.01
		echo "export Depends_c_d 	= 		\$(c_files:.c=.d)" 								>>Makefile.01
#		echo "Depends_c_o 	= 		\$(c_files:.c=.o)" 										>>Makefile.01
		echo ""  																						>>Makefile.01
		echo "export Depends_prg_d 	= 		\$(prg_files:.prg=.d)" 						>>Makefile.01
#		echo "Depends_prg_o 	= 		\$(prg_files:.prg=.o)" 									>>Makefile.01
		echo "export Depends_prg_po = 		\$(prg_files:.prg=.po)" 					>>Makefile.01
		echo ""  																						>>Makefile.01
		echo "export Depends_d		= 		\$(Depends_c_d) \$(Depends_prg_d)" 			>>Makefile.01
		echo "export Depend_h		= 		\$(ch_files) \$(h_files) \$(Main_h)" 		>>Makefile.01
		echo "export OBJ_files		= 		$OBJ_files" 										>>Makefile.01
		echo "export OBJS				= 		\$(sort \$(OBJ_files))" 						>>Makefile.01
		echo "export BIN				= 		$BIN$Suff_Exe" 									>>Makefile.01
		echo "export Local_BIN		= 		$Clip_B_Dir/$BIN" 								>>Makefile.01
# end function CreateMakefile_01

