#!/bin/sh
export C64=$(uname -m)
export ARCH=$(uname -m)
if [ -n "$ARCH" ] ; then
	if [[ $ARCH = "x86_64" ]] && [[ $C64 = "x86_64" ]] ; then
		ARCH=x86_64
		C64=64
	else
		ARCH=i586
		C64=""
	fi
fi
export C64
export ARCH
#source config/gen.in
set -e
./clean.sh
./cvs_update
./mksrc
./mksrc_p
./mkdeb
./mkrpm
./mktgz