function _recover_textget(obj)
  obj:badDate	:= @badDate()
  obj:assign 	:= @assign()
  obj:colorDisp := @colorDisp()
  obj:display 	:= @display()
  obj:killFocus := @killFocus()
  obj:setFocus 	:= @setFocus()
  obj:reset 	:= @reset()
  obj:undo 	:= @setFocus()
  obj:updateBuffer := @setFocus()
  obj:varGet 	:= @varGet()
  obj:varPut 	:= @varPut()

  obj:end 	:= @cur_end()
  obj:home 	:= @cur_home()
  obj:left 	:= @cur_left()
  obj:right 	:= @cur_right()
  obj:gotoPos 	:= @cur_goto()
  obj:toDecPos 	:= @toDecPos()
  obj:wordLeft 	:= @wordLeft()
  obj:wordRight	:= @wordRight()

  obj:backSpace	:= @backSpace()
  obj:delLeft	:= @backSpace()
  obj:delRight	:= @delRight()
  obj:delete	:= @delRight()
  obj:delEnd    := @delEnd()
  obj:delWordLeft  := @delWordLeft()
  obj:delWordRight := @delWordRight()

  obj:Insert 	:= @Insert()
  obj:InsertLine:= @InsertLine()
  obj:up	:= @cur_up()
  obj:down	:= @cur_down()
  obj:pgUp	:= @cur_pgUp()
  obj:pgDn	:= @cur_pgDn()
  obj:overStrike:= @overStrike()
  obj:hitTest 	:= @edit_hitTest()
  obj:__setColor:= @__setcolor()
return obj
