function _recover_radiogroup(obj)
   obj:addItem	:=@rg_addItem()
   obj:delItem	:=@rg_delItem()
   obj:display	:=@rg_display()
   obj:getAccel	:=@rg_getAccel()
   obj:getItem	:=@rg_getItem()
   obj:hitTest	:=@hitTest()
   obj:insItem	:=@rg_insItem()
   obj:killFocus:=@killFocus()
   obj:prevItem	:=@rg_prevItem()
   obj:nextItem	:=@rg_nextItem()
   obj:select	:=@rg_select()
   obj:setcolor	:=@rg_setcolor()
   obj:setFocus	:=@setFocus()
   obj:setstyle	:=@rg_setstyle()
   obj:__setColor:=@__setcolor()
   obj:__setValue:=@rg_setValue()
return obj
