static int
make_c_file(char *Arname, int argc, char **argv)
{
   int ret = 0, i;

   Coll coll;

   char *modp, *modbeg;

   FILE *file = 0;

   time_t ts;

   char name[64], *e, *s, arname[256];

   int nstatics;

   long size;

   strncpy(arname, Arname, sizeof(arname));
   s = strrchr(arname, '/');
   if (!s)
      s = arname;
   e = strrchr(s, '.');
   if (!e)
      e = s + strlen(s);
   strcpy(e, ".c");

#if 0
   tmpnam(tmp_file);
   strcat(tmp_file, ".pa");
#else
   /*snprintf(tmp_file, sizeof(tmp_file), "/tmp/clipar.XXXXXX");
      mktemp(tmp_file);
      strcat(tmp_file, ".pa"); */
   snprintf(tmp_file, sizeof(tmp_file), "/tmp/clipar.%lx%lx.pa", (long) getpid(), (long) random());
#endif

   if (make_pa_file(tmp_file, argc, argv))
      goto err;

   init_Coll(&coll, free, NULL);

   read_file(tmp_file, &coll, NULL);
	if (coll.count_of_Coll < 1)
      error("%s have no modules", tmp_file);

   file = fopen(arname, "wb");
   if (!file)
      error("cannot open file '%s': %s", arname, strerror(errno));

   v_printf(0, "write file '%s'\n", arname);

   fprintf(file, "/*\n");
   fprintf(file, " *\tfile '%s', \n", arname);
   fprintf(file, " *\tautomatically generated by clipar\n");
   fprintf(file, " *\tfrom sources:\n");
   for (i = 0; i < argc; ++i)
      fprintf(file, " *\t%s\n", argv[i]);
   time(&ts);
   fprintf(file, " *\tat %s", ctime(&ts));
   fprintf(file, " */\n");

   fprintf(file, "\n#include \"ci_clip.h\"\n\n");

   s = strrchr(arname, '/');
   if (!s)
      s = arname;
   e = strrchr(s, '.');
   if (!e)
      e = s + strlen(s);
   strcpy(name, "clip__PCODE_");
   i = strlen(name);
   memcpy(name + i, s, e - s);
   name[i + (e - s)] = 0;

	modp = (char *) coll.items_of_Coll[0];
   modbeg = M_OFFS(modp, 2, 0);
   nstatics = *(long *) M_OFFS(modp, 3, 0);

   fprintf(file, "static ClipVar %s_statics[] =\n{\n", name);
   for (i = 0; i < nstatics; ++i)
      fprintf(file, "\t{0,0},\n");
   fprintf(file, "\n};\n");
   fprintf(file, "\nstatic char %s_body[]=\n{\n", name);
	for (size = 0, i = 0; i < coll.count_of_Coll; ++i)
   {
		char *mp = (char *) coll.items_of_Coll[i];

      long modlen = *(long *) M_OFFS(mp, 1, 0);

      long j, k;

      modlen += 8 + 2 * sizeof(long);

      for (j = 0; j < modlen;)
      {
	 fprintf(file, "\t");
	 for (k = 0; k < 32 && j < modlen; ++j, ++k, ++size)
	    fprintf(file, "%d,", mp[j]);
	 fprintf(file, "\n");
      }
   }
   fprintf(file, "\n};\n");
   fprintf(file, "\nstruct ClipFile ");
   for (i = 0; i < strlen(name); ++i)
      fputc(toupper(name[i]), file);
   fprintf(file, " =\n{\n");
   fprintf(file, "\t1,\n");
   fprintf(file, "\t%s_body,\n", name);
   fprintf(file, "\t%ld,\n", size);
   fprintf(file, "\t3,\n");
   fprintf(file, "\t\"%s\",\n", arname);
   fprintf(file, "\t%s_statics,\n", name);
   fprintf(file, "\t3,\n");
   fprintf(file, "\t0,\n");
   fprintf(file, "\t0,\n");
   fprintf(file, "};\n\n");

   for (i = 0; i < strlen(name); ++i)
      name[i] = toupper(name[i]);

   fprintf(file, "\nClipModule %s_module =\n{\n ", name + 7);
   fprintf(file, "\t\"%s\",\n", name + 7);
   fprintf(file, "\t0,\n");
   fprintf(file, "\t0,\n");
   fprintf(file, "\t0,\n");
   fprintf(file, "\t&%s,\n", name);
   fprintf(file, "\t0,\n");
   fprintf(file, "\t0,\n");
   fprintf(file, "\t0,\n");
   fprintf(file, "};\n\n");

   v_printf(0, "done, %ld bytes\n", ftell(file));
   goto norm;
 err:
   ret = 1;
 norm:
   unlink(tmp_file);
   tmp_file[0] = 0;
   fclose(file);
   return ret;
}
