function _recover_datetime(obj)
	obj:date	:= @odt_date()
	obj:time	:= @odt_time()
	obj:year	:= @odt_year()
	obj:month	:= @odt_month()
	obj:day		:= @odt_day()
	obj:hour	:= @odt_hour()
	obj:min		:= @odt_min()
	obj:sec		:= @odt_sec()
	obj:msec	:= @odt_msec()

	obj:normalize	:= @odt_normalize()
	obj:add		:= @odt_add()
	obj:sub		:= @odt_sub()
return obj
