*********************
static function me_enableMenu()
local enable := ::__l_tobj
	::oMenu:enableStatus(HASH_SaveFile            , enable)
	::oMenu:enableStatus(HASH_Reload              , enable)
	::oMenu:enableStatus(HASH_ReadOnly            , enable)
	::oMenu:enableStatus(HASH_ListFiles           , enable)
	::oMenu:enableStatus(HASH_NextWindow          , enable)
	::oMenu:enableStatus(HASH_PrevWindow          , enable)
	::oMenu:enableStatus(HASH_CloseWindow         , enable)
	::oMenu:enableStatus(HASH_InsMode             , enable)
	::oMenu:enableStatus(HASH_SaveAsFile          , enable)
	::oMenu:enableStatus(HASH_LoadBlock           , enable)
	::oMenu:enableStatus(HASH_FindString          , enable)
	::oMenu:enableStatus(HASH_FindNext            , enable)
	::oMenu:enableStatus(HASH_FindPrev            , enable)
	::oMenu:enableStatus(HASH_FindReplace         , enable)
	::oMenu:enableStatus(HASH_MatchSymbolForward  , enable)
	::oMenu:enableStatus(HASH_MatchSymbolBackward , enable)
	::oMenu:enableStatus(HASH_MatchStructForward  , enable)
	::oMenu:enableStatus(HASH_MatchStructBackward , enable)
	::oMenu:enableStatus(HASH_Undo                , enable)
	::oMenu:enableStatus(HASH_FormatLine          , enable)
	::oMenu:enableStatus(HASH_FormatPart          , enable)
	::oMenu:enableStatus(HASH_Template            , enable)
	::oMenu:enableStatus(HASH_Macro               , enable)
	::oMenu:enableStatus(HASH_SingleGraphic       , enable)
	::oMenu:enableStatus(HASH_DoubleGraphic       , enable)
	::oMenu:enableStatus(HASH_ChooseCodePage      , enable)
	::oMenu:enableStatus(HASH_Print               , enable)
return .t.
