/*
	Copyright (C) 2001  ITK
	Author   : Uri (uri@itk.ru)
	License : (GPL) http://www.itk.ru/clipper/license.html
*/
**********************************************************************
#include "ci_config.ch"
#include "ci_set.ch"
#include "ci_fileio.ch"
#include "ci_common.ch"
#include "ci_error.ch"
#include "ci_dbinfo.ch"
#include "ci_error.ch"
**********************************************************************
#include "db_func/static___dbiInfo.ch"
#include "db_func/static__m6_copyrec.ch"
**********************************************************************
#include "db_func/__dbApp.ch"
#include "db_func/__dbAppDelim.ch"
#include "db_func/__dbAppSDF.ch"
#include "db_func/__dbCopy.ch"
#include "db_func/__dbCopyDelim.ch"
#include "db_func/__dbCopyOptimize.ch"
#include "db_func/__dbCopySDF.ch"
#include "db_func/__dbCopyStruct.ch"
#include "db_func/__dbCopyXStruct.ch"
#include "db_func/__dbCreate.ch"
#include "db_func/__dbDelim.ch"
#include "db_func/__dbDelimOptimize.ch"
#include "db_func/__DbList.ch"
#include "db_func/__DbListOptimize.ch"
#include "db_func/__dbSDF.ch"
#include "db_func/__dbSDFOptimize.ch"
#include "db_func/__dbSort.ch"
#include "db_func/__dbSortOptimize.ch"
#include "db_func/__dbTotal.ch"
#include "db_func/__dbTotalOptimize.ch"
#include "db_func/__DBUPDATE.ch"
#include "db_func/__LabelFormOptimize.ch"
#include "db_func/__ReportFormOptimize.ch"
#include "db_func/aliasesInfo.ch"
#include "db_func/dbCheckStructure.ch"
#include "db_func/dbCreate.ch"
#include "db_func/dbStructInfo.ch"
#include "db_func/fieldblock.ch"
#include "db_func/fieldwblock.ch"
#include "db_func/indexesInfo.ch"
#include "db_func/m6_Copy.ch"
#include "db_func/m6_CopyDelim.ch"
#include "db_func/m6_CopySDF.ch"
#include "db_func/m6_CopyToArray.ch"
#include "db_func/m6_CountFor.ch"
#include "db_func/m6_LabelForm.ch"
#include "db_func/m6_ListFor.ch"
#include "db_func/m6_ReportForm.ch"
#include "db_func/m6_Search.ch"
#include "db_func/m6_SortFor.ch"
#include "db_func/m6_TotalFor.ch"
#include "db_func/recordInfo.ch"
#include "db_func/tmpalias.ch"
#include "db_func/waitRddLock.ch"
**********************************************************************

