
/*
	This file contains an array of all clip commands as long words
*/

#xtranslate ACCE 					=> ACCEPT
#xtranslate ADDI 					=> ADDITIVE
#xtranslate ALIA 					=> ALIAS
#xtranslate ALL 					=> ALL
#xtranslate ALTE 					=> ALTERNATE
#xtranslate AMER 					=> AMERICAN
#xtranslate ANSI 					=> ANSI
#xtranslate APPE 					=> APPEND
#xtranslate ARRA 					=> ARRAY
#xtranslate ASCE 					=> ASCENDING
#xtranslate ASSE 					=> ASSERT
#xtranslate AUTO 					=> AUTOOPEN
#xtranslate AUTOO 				=> AUTOORDER
#xtranslate AUTOP 				=> AUTOOPEN
#xtranslate AUTOR 				=> AUTOORDER
#xtranslate AUTOS 				=> AUTOSHARE
#xtranslate AT 					=> AT
#xtranslate AVER 					=> AVERAGE
#xtranslate BELL 					=> BELL
#xtranslate BITM 					=> BITMAP
#xtranslate BITMA 				=> BITMAPS
#xtranslate BLAN 					=> BLANK
#xtranslate BOTT 					=> BOTTOM
#xtranslate BOX 					=> BOX
#xtranslate BRIT 					=> BRITISH
#xtranslate BUFF 					=> BUFFER
#xtranslate BUFFE 				=> BUFFERED
#xtranslate BUFFER 				=> BUFFERING
#xtranslate CANC 					=> CANCEL
#xtranslate CAPO 					=> CAPOFF
#xtranslate CAPT 					=>CAPTION
#xtranslate CENT 					=>CENTER
#xtranslate CENTR 				=>CENTER
#xtranslate CENTU 				=>CENTURY
#xtranslate CHAR 					=>CHARSET
#xtranslate CHEC 					=>CHECKBOX
#xtranslate CLEA 					=>CLEAR
#xtranslate CLIP 					=>CLIPPER
#xtranslate CLIPPER5 			=>CLIPPER50
#xtranslate CLIPPER52 			=>CLIPPER52
#xtranslate CLIPPER53 			=>CLIPPER53
#xtranslate CLOS 					=>CLOSE
#xtranslate CLS 					=>CLS
#xtranslate COL 					=>COL
#xtranslate COLO 					=>COLOR
#xtranslate COLOU 				=>COLOR
#xtranslate COMM 					=>COMMIT
#xtranslate CONF 					=>CONFIRM
#xtranslate CONN 					=>CONNECT
#xtranslate CONS 					=>CONSOLE
#xtranslate CONT 					=>CONTINUE
#xtranslate COPY 					=>COPY
#xtranslate COUN 					=>COUNT
#xtranslate CREA 					=>CREATE
#xtranslate CURS 					=>CURSOR
#xtranslate CUST 					=>CUSTOM
#xtranslate DATA 					=>DATABASE
#xtranslate DATABASES 			=>DATABASES
#xtranslate DATE 					=>DATE
#xtranslate DBF 					=>DBF
#xtranslate DECI 					=>DECIMALS
#xtranslate DEF 					=>DEF
#xtranslate DEFA 					=>DEFAULT
#xtranslate DELE 					=>DELETE
#xtranslate DELETED 				=>DELETED
#xtranslate DELI 					=>DELIMITED
#xtranslate DELIMITE 			=>DELIMITERS
#xtranslate DESC 					=>DESCENDING
#xtranslate DEVI 					=>DEVICE
#xtranslate DIR 					=>DIR
#xtranslate DIRE 					=>DIRECTORY
#xtranslate DISP 					=>DISPBOX
#xtranslate DISPL 				=>DISPLAY
#xtranslate DO 					=>DO
#xtranslate DOUBLE 				=>DOUBLE
#xtranslate DROPDOWN 			=>DROPDOWN
#xtranslate DUMP 					=>DUMP
#xtranslate ECHO 					=>ECHO
#xtranslate EJECT 				=>EJECT
#xtranslate EMPTY 				=>EMPTY
#xtranslate END 					=>END
#xtranslate ENDC 					=>ENDCASE
#xtranslate ENDD 					=>ENDDO
#xtranslate ENDF 					=>ENDFOR
#xtranslate ENDI 					=>ENDIF
#xtranslate ENDN 					=>ENDNEXT
#xtranslate ENDS 					=>ENDSEQUENCE
#xtranslate ENDS 					=>ENDSWITCH
#xtranslate EPOC 					=>EPOCH
#xtranslate ERAS 					=>ERASE
#xtranslate ESCA 					=>ESCAPE
#xtranslate EVAL 					=>EVAL
#xtranslate EVEN 					=>EVENTMASK
#xtranslate EVER 					=>EVERY
#xtranslate EXAC 					=>EXACT
#xtranslate EXCE 					=>EXCEPT
#xtranslate EXCL 					=>EXCLUSIVE
#xtranslate EXIT 					=>EXIT
#xtranslate EXTE 					=>EXTENDED
#xtranslate EXTER 				=>EXTERNAL
#xtranslate FIELD 				=>FIELD
#xtranslate FIELDS 				=>FIELDS
#xtranslate FILE 					=>FILE
#xtranslate FILEI 				=>FILEIO
#xtranslate FILT 					=>FILTER
#xtranslate FILTR 				=>FILTER
#xtranslate FIND 					=>FIND
#xtranslate FIXE 					=>FIXED
#xtranslate FOCU 					=>FOCUS
#xtranslate FOPE 					=>FOPEN
#xtranslate FOR 					=>FOR
#xtranslate FORM 					=>FORM
#xtranslate FORMA 				=>FORMAT
#xtranslate FOXP 					=>FOXPRO
#xtranslate FREN 					=>FRENCH
#xtranslate FROM 					=>FROM
#xtranslate FUNC 					=>FUNCTION
#xtranslate GERM 					=>GERMAN
#xtranslate GET 					=>GET
#xtranslate GETS 					=>GETS
#xtranslate GO 					=>GO
#xtranslate GOBO 					=>GO BOTTOM
#xtranslate GOTO 					=>GOTO
#xtranslate GOTOP 				=>GO TOP
#xtranslate GUIS 					=>GUISEND
#xtranslate HEAD 					=>HEADING
#xtranslate HOST 					=>HOST
#xtranslate HOUR 					=>HOURS
#xtranslate ID 					=>ID
#xtranslate ID_G 					=>ID_GENERATOR
#xtranslate IDLE 					=>IDLE
#xtranslate IF 					=>IF
#xtranslate IIF 					=>IIF
#xtranslate IN 					=>IN
#xtranslate INDE 					=>INDEX
#xtranslate INDEXE 				=>INDEXES
#xtranslate INKE 					=>INKEY
#xtranslate INPU 					=>INPUT
#xtranslate INSE 					=>INSERT
#xtranslate INTE 					=>INTENSITY
#xtranslate INTO 					=>INTO
#xtranslate ISOL 					=>ISOLATION
#xtranslate ITAL 					=>ITALIAN
#xtranslate JAPA 					=>JAPANESE
#xtranslate JOIN 					=>JOIN
#xtranslate KEY 					=>KEY
#xtranslate KEYB 					=>KEYBOARD
#xtranslate LABE 					=>LABEL
#xtranslate LAST 					=>LAST
#xtranslate LEVE 					=>LEVEL
#xtranslate LIKE 					=>LIKE
#xtranslate LIMI 					=>LIMIT
#xtranslate LIST 					=>LIST
#xtranslate LISTB 				=>LISTBOX
#xtranslate LOCA 					=>LOCATE
#xtranslate LOCK 					=>LOCKSTYLE
#xtranslate LOGF 					=>LOGFILE
#xtranslate LOGL 					=>LOGLEVEL
#xtranslate LOOP 					=>LOOP
#xtranslate MACR 					=>MACRO_IN_STRING
#xtranslate MAP 					=>MAP
#xtranslate MARG 					=>MARGIN
#xtranslate MBLO 					=>MBLOCKSIZE
#xtranslate MEMB 					=>MEMBUF
#xtranslate MEMO 					=>MEMOBLOCK
#xtranslate MEMOR 				=>MEMORY
#xtranslate MENU 					=>MENU
#xtranslate MESS 					=>MESSAGE
#xtranslate MFIL 					=>MFILEEXT
#xtranslate MILL 					=>MILLISEC
#xtranslate MODE 					=>MODE
#xtranslate MSG 					=>MSG
#xtranslate MULT 					=>MULTILOCKS
#xtranslate NEAR 					=>NEAR
#xtranslate NEW 					=>NEW
#xtranslate NEXT 					=>NEXT
#xtranslate NIL 					=>NIL
#xtranslate NOCO 					=>NOCONSOLE
#xtranslate NOEJ 					=>NOEJECT
#xtranslate NOFE 					=>NOFETCH
#xtranslate NONC 					=>NONCOMPACT
#xtranslate NOOP 					=>NOOPTIMIZE
#xtranslate OF 					=>OF
#xtranslate OFF 					=>OFF
#xtranslate ON 					=>ON
#xtranslate OPTI 					=>OPTIMIZE
#xtranslate OPTIO 				=>OPTION
#xtranslate OPTIONS 				=>OPTIONS
#xtranslate ORDE 					=>ORDER
#xtranslate ORDERS 				=>ORDERS
#xtranslate OTHE 					=>OTHERWISE
#xtranslate PACK 					=>PACK
#xtranslate PARA 					=>PARAMETERS
#xtranslate PASS 					=>PASSWORD
#xtranslate PATH 					=>PATH
#xtranslate PICT 					=>PICTURE
#xtranslate PLAI 					=>PLAIN
#xtranslate PORT 					=>PORT
#xtranslate PRIN 					=>PRINT
#xtranslate PRINTE 				=>PRINTER
#xtranslate PROC 					=>PROCEDURE
#xtranslate PROM 					=>PROMPT
#xtranslate PUSH 					=>PUSHBUTTON
#xtranslate QUER 					=>QUERY
#xtranslate QUIT 					=>QUIT
#xtranslate RADI 					=>RADIOGROUP
#xtranslate RAND 					=>RANDOM
#xtranslate RANG 					=>RANGE
#xtranslate RATI 					=>RATIONAL
#xtranslate RDBM 					=>RDBMS
#xtranslate READ 					=>READ
#xtranslate READO 				=>READONLY
#xtranslate RECA 					=>RECALL
#xtranslate RECH 					=>RECHECK
#xtranslate RECO 					=>RECORD
#xtranslate RECN 					=>RECNO
#xtranslate REFR 					=>REFRESH
#xtranslate REGU 					=>REGULAR
#xtranslate REIN 					=>REINDEX
#xtranslate RELA 					=>RELATION
#xtranslate RELE 					=>RELEASE
#xtranslate RENA 					=>RENAME
#xtranslate REPE 					=>REPEAT
#xtranslate REPL 					=>REPLACE
#xtranslate REPO 					=>REPORT
#xtranslate REQU 					=>REQUEST
#xtranslate REST 					=>REST
#xtranslate RESTO 				=>RESTORE
#xtranslate ROW 					=>ROW
#xtranslate ROWS 					=>ROWSET
#xtranslate RUN 					=>RUN
#xtranslate SAFE 					=>SAFETY
#xtranslate SAVE 					=>SAVE
#xtranslate SAY 					=>SAY
#xtranslate SCOR 					=>SCOREBOARD
#xtranslate SCOP 					=>SCOPE
#xtranslate SCOPEB 				=>SCOPEBOTTOM
#xtranslate SCOPET 				=>SCOPETOP
#xtranslate SCREE 				=>SCREEN
#xtranslate SCROL 				=>SCROLLBAR
#xtranslate SDF 					=>SDF
#xtranslate SEAR					=>SEARCH
#xtranslate SECO 					=>SECONDS
#xtranslate SEEK 					=>SEEK
#xtranslate SELE 					=>SELECT
#xtranslate SEND 					=>SEND
#xtranslate SEQU 					=>SEQUENCE
#xtranslate SET 					=>SET
#xtranslate SHAR 					=>SHARED
#xtranslate SIX 					=>SIX
#xtranslate SIZE 					=>SIZE
#xtranslate SKIP 					=>SKIP
#xtranslate SOFT 					=>SOFTSEEK
#xtranslate SORT 					=>SORT
#xtranslate STAT 					=>STATE
#xtranslate STATU 				=>STATUS
#xtranslate STEP 					=>STEP
#xtranslate STOR 					=>STORE
#xtranslate STRI 					=>STRICTREAD
#xtranslate STRU 					=>STRUCTURE
#xtranslate STYL 					=>STYLE
#xtranslate SUBI 					=>SUBINDEX
#xtranslate SUM 					=>SUM
#xtranslate SUMM 					=>SUMMARY
#xtranslate SWIT 					=>SWITCH
#xtranslate TAG 					=>TAG
#xtranslate TALK 					=>TALK
#xtranslate TBRO 					=>TBROWSE
#xtranslate TEMP 					=>TEMPORARY
#xtranslate TEXT 					=>TEXT
#xtranslate TEXTB 				=>TEXTBLOCK
#xtranslate TO 					=>TO
#xtranslate TOKE 					=>TOKENNEXT
#xtranslate TOP 					=>TOP
#xtranslate TOTA 					=>TOTAL
*#xtranslate xtranslate 			=>xtranslate
#xtranslate TYPE 					=>TYPE
#xtranslate TYPEA					=>TYPEAHEAD
#xtranslate TYPEC 				=>TYPECHECK
#xtranslate UNIQ 					=>UNIQUE
#xtranslate UNLO 					=>UNLOCK
#xtranslate UNLOCKA 				=>UNLOCKALL
#xtranslate UNTI 					=>UNTIL
#xtranslate UPDA 					=>UPDATE
#xtranslate USA 					=>USA
#xtranslate USE 					=>USE
#xtranslate USEC 					=>USECURRENT
#xtranslate USER 					=>USER
#xtranslate UTF8 					=>UTF8TERM
#xtranslate VALI 					=>VALID
#xtranslate VIA 					=>VIA
#xtranslate VIDE 					=>VIDEOMODE
#xtranslate WAIT 					=>WAIT
#xtranslate WHEN 					=>WHEN
#xtranslate WHIL 					=>WHILE
#xtranslate WINE 					=>WINEXEC
#xtranslate WITH 					=>WITH
#xtranslate WRAP 					=>WRAP
#xtranslate X 						=>X
#xtranslate Y 						=>Y
#xtranslate ZAP 					=>ZAP
