init procedure dtools_init
	monates:={}
	asize(monates,12)
	monates[1]=DATE_MONATE1
	monates[2]=DATE_MONATE2
	monates[3]=DATE_MONATE3
	monates[4]=DATE_MONATE4
	monates[5]=DATE_MONATE5
	monates[6]=DATE_MONATE6
	monates[7]=DATE_MONATE7
	monates[8]=DATE_MONATE8
	monates[9]=DATE_MONATE9
	monates[10]=DATE_MONATE10
	monates[11]=DATE_MONATE11
	monates[12]=DATE_MONATE12
	days:={}
	asize(days,7)
	days[1]=DATE_WEEK1
	days[2]=DATE_WEEK2
	days[3]=DATE_WEEK3
	days[4]=DATE_WEEK4
	days[5]=DATE_WEEK5
	days[6]=DATE_WEEK6
	days[7]=DATE_WEEK7
return
