function _recover_popupmenu(obj)
  obj:additem	:= @m_additem()
  obj:delItem	:= @m_delItem()
  obj:insItem	:= @m_insItem()
  obj:getAccel	:= @m_getAccel()
  obj:getFirst	:= @m_getFirst()
  obj:getItem	:= @m_getItem()
  obj:setItem	:= @m_setItem()
  obj:getLast	:= @m_getLast()
  obj:getNext	:= @m_getNext()
  obj:getPrev	:= @m_getPrev()
  obj:select	:= @m_select()
  obj:display	:= @pp_display()
  obj:hittest	:= @pp_hittest()
  obj:close	:= @pp_close()
  obj:open	:= @pp_open()
  obj:getShortct:= @pp_Shortct()
  obj:__resize	:= @__resize()
  obj:enableStatus	:= @pp_Estatus()
  obj:disableStatus	:= @pp_Dstatus()
  obj:_Status	:= @m__status()
return obj
