function _recover_topbarmenu(obj)
  obj:additem	:= @m_additem()
  obj:delItem	:= @m_delItem()
  obj:insItem	:= @m_insItem()
  obj:getAccel	:= @m_getAccel()
  obj:getFirst	:= @m_getFirst()
  obj:getItem	:= @m_getitem()
  obj:setItem	:= @m_setitem()
  obj:getLast	:= @m_getLast()
  obj:getNext	:= @m_getNext()
  obj:getPrev	:= @m_getPrev()
  obj:select	:= @m_select()
  obj:display	:= @tb_display()
  obj:hittest	:= @tb_hittest()
  obj:getShortct:= @pp_Shortct()
  obj:enableStatus	:= @tb_Estatus()
  obj:disableStatus	:= @tb_Dstatus()
  obj:_Status	:= @m__status()
return obj
