**********************************************************************
**********************************************************************
#include <dbfsql_prg/static__sqlflush.prg>
#include <dbfsql_prg/static_atany.prg>
// BLOB-functions
#include <dbfsql_prg/static_blobclose.prg>
#include <dbfsql_prg/static_blobcreate.prg>
#include <dbfsql_prg/static_blobexport.prg>
#include <dbfsql_prg/static_blobimport.prg>
#include <dbfsql_prg/static_blobopen.prg>
#include <dbfsql_prg/static_blobread.prg>
#include <dbfsql_prg/static_blobseek.prg>
#include <dbfsql_prg/static_blobtell.prg>
#include <dbfsql_prg/static_blobunlink.prg>
#include <dbfsql_prg/static_blobwrite.prg>

#include <dbfsql_prg/static_conncommand.prg>
#include <dbfsql_prg/static_conncommit.prg>
#include <dbfsql_prg/static_conncreaterowset.prg>
#include <dbfsql_prg/static_conndestroy.prg>
#include <dbfsql_prg/static_connrollback.prg>
#include <dbfsql_prg/static_connstart.prg>
#include <dbfsql_prg/static_conntestparser.prg>
#include <dbfsql_prg/static_parsarray.prg>
#include <dbfsql_prg/static_parlocwrite.prg>
#include <dbfsql_prg/static_parsmacros.prg>
#include <dbfsql_prg/static_rowsetappend.prg>
#include <dbfsql_prg/static_rowsetbof.prg>
#include <dbfsql_prg/static_rowsetbrowse.prg>
#include <dbfsql_prg/static_rowsetcreateorder.prg>
#include <dbfsql_prg/static_rowsetdelete.prg>
#include <dbfsql_prg/static_rowsetdestroy.prg>
#include <dbfsql_prg/static_rowseteof.prg>
#include <dbfsql_prg/static_rowsetfetchall.prg>
#include <dbfsql_prg/static_rowsetfetched.prg>
#include <dbfsql_prg/static_rowsetfieldbinary.prg>
#include <dbfsql_prg/static_rowsetfieldblock.prg>
#include <dbfsql_prg/static_rowsetfielddec.prg>
#include <dbfsql_prg/static_rowsetfieldlen.prg>
#include <dbfsql_prg/static_rowsetfieldname.prg>
#include <dbfsql_prg/static_rowsetfieldno.prg>
#include <dbfsql_prg/static_rowsetfieldnullable.prg>
#include <dbfsql_prg/static_rowsetfieldunsigned.prg>
#include <dbfsql_prg/static_rowsetfieldtype.prg>
#include <dbfsql_prg/static_rowsetfieldtypesql.prg>
#include <dbfsql_prg/static_rowsetfromclip.prg>
#include <dbfsql_prg/static_rowsetgetvalue.prg>
#include <dbfsql_prg/static_rowsetgobottom.prg>
#include <dbfsql_prg/static_rowsetgoto.prg>
#include <dbfsql_prg/static_rowsetgotop.prg>
#include <dbfsql_prg/static_rowsetkeyno.prg>
#include <dbfsql_prg/static_rowsetlastrec.prg>
#include <dbfsql_prg/static_rowsetnfields.prg>
#include <dbfsql_prg/static_rowsetread.prg>
#include <dbfsql_prg/static_rowsetrecno.prg>
#include <dbfsql_prg/static_rowsetrefresh.prg>
#include <dbfsql_prg/static_rowsetrefreshcurrent.prg>
#include <dbfsql_prg/static_rowsetseek.prg>
#include <dbfsql_prg/static_rowsetsetorder.prg>
#include <dbfsql_prg/static_rowsetsetvalue.prg>
#include <dbfsql_prg/static_rowsetskip.prg>
#include <dbfsql_prg/static_rowsettoclip.prg>
#include <dbfsql_prg/static_rowsetwrite.prg>
**********************************************************************
#include <dbfsql_prg/_fromrdbmstoclip.prg>
#include <dbfsql_prg/_fromcliptordbms.prg>
#include <dbfsql_prg/connectnew.prg>
#include <dbfsql_prg/numno.prg>
**********************************************************************

