static void
getEnvironment()
{
   GETENV("CC");
   GETENV("CFLAGS");
   GETENV("COPT");
   GETENV("CDBG");
   GETENV("OUT_FLAG");
   GETENV("INCLUDE_FLAG");
   GETENV("OBJSUF");
   GETENV("SOBJSUF");
   GETENV("LIBSUF");
   GETENV("SLIBSUF");
   GETENV("COMPILE_FLAG");
   GETENV("SFLAGS");
   GETENV("CLIPLIB");
   GETENV("CLIPLIBS");
   GETENV("CLIPROOT");
   GETENV("CLIP_LOCALE_ROOT");
   GETENV("CLIPSLIB");
   GETENV("CLIP_CMDSTR");
   GETENV("CLIP_MODULE");
   GETENV("CLIP_NAMES");
#ifdef USE_AS
   GETENV("CLIP_ASM");
#endif

}
