function _recover_dialogbox(obj)
       obj:drawBox      := @db_drawBox()
       obj:down         := @db_down()
       obj:up           := @db_up()
       obj:left         := @db_left()
       obj:right        := @db_right()
       obj:bottom       := @db_bottom()
       obj:top          := @db_top()
       obj:home         := @db_home()
       obj:end          := @db_end()
       obj:pageDown     := @db_pageDown()
       obj:pageUp       := @db_pageUp()
       obj:select	:= @db_select()
       obj:enter	:= @db_enter()
       obj:delete	:= @db_delete()
       obj:insert	:= @db_insert()
       obj:backspace	:= @db_backspace()
       obj:refresh	:= @db_refresh()
       obj:handleKey	:= @db_handleKey()
       obj:check_line	:= @db_check_line()
       obj:killFocus	:= @db_killFocus()
       obj:goto		:= @db_goto()
       obj:goItem	:= @db_goItem()
       obj:close	:= @db_close()
       obj:destroy	:= @db_destroy()

       obj:menu		:= @db_menu_create()
       obj:init		:= @db_init()
       obj:Text		:= @db_Text()
       obj:Button	:= @db_Button()
       obj:Get		:= @db_Get()
       obj:Check	:= @db_Check()
       obj:Radio	:= @db_Radio()
       obj:GetText	:= @db_GetText()
       obj:curWord	:= @db_curWord()
       obj:getStrElem	:= @db_getStrElem()
       obj:getString	:= @db_getString()
       obj:findStr	:= @db_find()
       obj:makeStr	:= @db_makeStr()
       obj:cancelBlock	:= @db_cancelBlock()

       obj:setValue	:= @db_setValue()
       obj:__setColor 	:= @__setcolor()
return obj
