int
main(int argc, char **argv)
{
   char buf[4096];

   char word1[80], word2[80], word3[80];

   int i;

   FILE *in;

   time_t tbuf;

   if (argc < 1)
      return 0;

   strcpy(buf, "nm");
   for (i = 1; i < argc; i++)
   {
      strcat(buf, " ");
      strcat(buf, argv[i]);
   }

   in = popen(buf, "r");

   if (!in)
   {
      perror("genlist");
      exit(2);
   }

   printf("/*\n");
   printf(" *\tautomatically generated by 'genlist'\n");
   time(&tbuf);
   printf(" *\tat %s", ctime(&tbuf));
   printf(" *\tfrom sources:\n");
   for (i = 1; i < argc; ++i)
      printf(" *\t%s\n", argv[i]);
   printf(" */\n");

   printf("\n#include \"ci_clip.h\"\n\n");

   printf("struct ClipNameEntry _cfunctions[]=\n{\n");
   while (fgets(buf, sizeof(buf), in) != NULL)
   {
      char *s;

      int n = sscanf(buf, "%s %s %s", word1, word2, word3);

      if (n < 3)
	 continue;
      if (strcmp(word2, "T"))
	 continue;
      for (s = word3; *s; ++s)
	 if (!isupper(*s) && !isdigit(*s) && *s != '_')
	    goto next;

      printf("\t{ %s, \"%s\" },\n", word3, word3);
    next:
      ;
   }
   printf("\t{ 0, 0 }\n");
   printf("};\n\n");

   pclose(in);
   return 0;
}
