//#define DEBUG

/*
    Copyright (C) 2001  ITK
    Author   : Uri (uri@itk.ru)
    License : (GPL) http://www.itk.ru/clipper/license.html
*/
******************************************************************
#include "ci_set.ch"
#include "ci_lang.ch"
#include "ci_getexit.ch"
#include "ci_date.ch"
#include "ci_button.ch"
#include "ci_config.ch"
#include "ci_inkey.ch"
**********************************************************************
#include "get_obj/static___analizepic.ch"
#include "get_obj/static___checksym.ch"
#include "get_obj/static___fillbuffer.ch"
#include "get_obj/static___get_split_by_picture.ch"
#include "get_obj/static___set_default_keys.ch"
#include "get_obj/static___setkey.ch"
#include "get_obj/static___tostring.ch"
#include "get_obj/static___updateinfo.ch"
#include "get_obj/static__display.ch"
#include "get_obj/static_assign.ch"
#include "get_obj/static_backspace.ch"
#include "get_obj/static_baddate.ch"
#include "get_obj/static_colordisp.ch"
#include "get_obj/static_cur_end.ch"
#include "get_obj/static_cur_goto.ch"
#include "get_obj/static_cur_home.ch"
#include "get_obj/static_cur_left.ch"
#include "get_obj/static_cur_right.ch"
#include "get_obj/static_cur_setpos.ch"
#include "get_obj/static_delend.ch"
#include "get_obj/static_delright.ch"
#include "get_obj/static_delwordleft.ch"
#include "get_obj/static_delwordright.ch"
#include "get_obj/static_display.ch"
#include "get_obj/static_get_hittest.ch"
#include "get_obj/static_get_setcolor.ch"
#include "get_obj/static_get_undo.ch"
#include "get_obj/static_get_width.ch"
#include "get_obj/static_insert.ch"
#include "get_obj/static_killfocus.ch"
#include "get_obj/static_overstrike.ch"
#include "get_obj/static_reload.ch"
#include "get_obj/static_reset.ch"
#include "get_obj/static_setfocus.ch"
#include "get_obj/static_todecpos.ch"
#include "get_obj/static_untransform.ch"
#include "get_obj/static_updatebuffer.ch"
#include "get_obj/static_varget.ch"
#include "get_obj/static_varput.ch"
#include "get_obj/static_wordleft.ch"
#include "get_obj/static_wordright.ch"
**********************************************************************
#include "get_obj/___get.ch"
#include "get_obj/__cget__.ch"
#include "get_obj/__get.ch"
#include "get_obj/__get__.ch"
#include "get_obj/__caplength.ch"
#include "get_obj/__saycaption.ch"
#include "get_obj/__splitcolors.ch"
#include "get_obj/_recover_get.ch"
#include "get_obj/devoutpict.ch"
#include "get_obj/getreadvar.ch"
#include "get_obj/getnew.ch"
#include "get_obj/trans.ch"
#include "get_obj/transform.ch"
**********************************************************************
