/*
    Copyright (C) 2001  ITK
    Authors : Uri (uri@itk.ru), Alena (alena@itk.ru)
    License : (GPL) http://www.itk.ru/clipper/license.html
*/
**********************************************************************
#include "ci_config.ch"
**********************************************************************
#include "html_obj/static_html_adddata.ch"
#include "html_obj/static_html_addoption.ch"
#include "html_obj/static_html_addtag.ch"
#include "html_obj/static_html_bgimage.ch"
#include "html_obj/static_html_center.ch"
#include "html_obj/static_html_checkbox.ch"
#include "html_obj/static_html_closetag.ch"
#include "html_obj/static_html_endfont.ch"
#include "html_obj/static_html_endfontall.ch"
#include "html_obj/static_html_endform.ch"
#include "html_obj/static_html_endframeset.ch"
#include "html_obj/static_html_endlist.ch"
#include "html_obj/static_html_endmarquee.ch"
#include "html_obj/static_html_endselect.ch"
#include "html_obj/static_html_endtable.ch"
#include "html_obj/static_html_endtcell.ch"
#include "html_obj/static_html_endtrow.ch"
#include "html_obj/static_html_form.ch"
#include "html_obj/static_html_formfile.ch"
#include "html_obj/static_html_formget.ch"
#include "html_obj/static_html_formhidden.ch"
#include "html_obj/static_html_formpasswd.ch"
#include "html_obj/static_html_formreset.ch"
#include "html_obj/static_html_formsubmit.ch"
#include "html_obj/static_html_formtext.ch"
#include "html_obj/static_html_frame.ch"
#include "html_obj/static_html_frameset.ch"
#include "html_obj/static_html_hline.ch"
#include "html_obj/static_html_imageurl.ch"
#include "html_obj/static_html_inputimage.ch"
#include "html_obj/static_html_list.ch"
#include "html_obj/static_html_listitem.ch"
#include "html_obj/static_html_marquee.ch"
#include "html_obj/static_html_multicol.ch"
#include "html_obj/static_html_newline.ch"
#include "html_obj/static_html_pagecolor.ch"
#include "html_obj/static_html_paragraph.ch"
#include "html_obj/static_html_putbreak.ch"
#include "html_obj/static_html_putheading.ch"
#include "html_obj/static_html_putimage.ch"
#include "html_obj/static_html_qout.ch"
#include "html_obj/static_html_qqout.ch"
#include "html_obj/static_html_radiobox.ch"
#include "html_obj/static_html_say.ch"
#include "html_obj/static_html_saycolor.ch"
#include "html_obj/static_html_select.ch"
#include "html_obj/static_html_setfont.ch"
#include "html_obj/static_html_setfonttype.ch"
#include "html_obj/static_html_space.ch"
#include "html_obj/static_html_startfont.ch"
#include "html_obj/static_html_startform.ch"
#include "html_obj/static_html_startframeset.ch"
#include "html_obj/static_html_startlist.ch"
#include "html_obj/static_html_startmarquee.ch"
#include "html_obj/static_html_startselect.ch"
#include "html_obj/static_html_starttable.ch"
#include "html_obj/static_html_starttcell.ch"
#include "html_obj/static_html_starttrow.ch"
#include "html_obj/static_html_table.ch"
#include "html_obj/static_html_tcell.ch"
#include "html_obj/static_html_text.ch"
#include "html_obj/static_html_textcolor.ch"
#include "html_obj/static_html_thcell.ch"
#include "html_obj/static_html_trow.ch"
#include "html_obj/static_html_url.ch"
#include "html_obj/static_loadUrl.ch"
#include "html_obj/static_writeDocument.ch"
#include "html_obj/static_writetofile.ch"
#include "html_obj/static_WriteToHttp.ch"
**********************************************************************
#include "html_obj/htmlnew.ch"
**********************************************************************
