#	Created automatically by 'configure'
#

#
#	Compile flags
#
OSNAME='LINUX'
DLLIB='-ldl'
CYGFLAGS=''
COMPILER='gcc'
INSTALL_LIB='/usr/lib'
INSTALL_INCLUDE='/usr/include'
LIBDIRS='-L. -L/usr/lib -L/usr/lib/X11 -L/usr/X11R6/lib'
INCLUDEDIRS='-I. -I/usr/include/freetype2 -I/usr/include/freetype2/freetype -I/usr/include/X11 -I/usr/X11R6/include -I/usr/X11R6/include/X11 -I/usr/include'
LIBPNG='-lpng'
LIBJPEG='-ljpeg'
LIBFREETYPE='-lfreetype'
LIBXPM='-lXpm -lX11'

